import type { Product, Order } from "./types"

// Mock product data for development
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Fresh Tomatoes",
    description: "Locally grown red tomatoes, perfect for cooking",
    price: 2.5,
    unit: "kg",
    category: "vegetables",
    stock_quantity: 50,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Green Lettuce",
    description: "Fresh crispy lettuce leaves",
    price: 1.8,
    unit: "head",
    category: "vegetables",
    stock_quantity: 30,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Bananas",
    description: "Sweet ripe bananas",
    price: 3.2,
    unit: "kg",
    category: "fruits",
    stock_quantity: 25,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Carrots",
    description: "Fresh orange carrots",
    price: 2.0,
    unit: "kg",
    category: "vegetables",
    stock_quantity: 40,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "White Rice",
    description: "Premium quality white rice",
    price: 4.5,
    unit: "kg",
    category: "grains",
    stock_quantity: 100,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Red Onions",
    description: "Fresh red onions for cooking",
    price: 1.5,
    unit: "kg",
    category: "vegetables",
    stock_quantity: 60,
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    customer_name: "John Doe",
    customer_phone: "+1234567890",
    customer_email: "john@example.com",
    delivery_address: "123 Main St, City",
    total_amount: 15.3,
    status: "confirmed",
    payment_status: "paid",
    payment_method: "mobile_money",
    notes: "Please call when you arrive",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "order-2",
    customer_name: "Jane Smith",
    customer_phone: "+1234567891",
    delivery_address: "456 Oak Ave, City",
    total_amount: 8.7,
    status: "preparing",
    payment_status: "pending",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
]
